server:
  port: 8052

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8051/eureka/

spring:
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

---
spring:
  profiles: deployment
  zipkin:
    baseUrl: http://zipkin:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8051/eureka/