host:
  zipkin: localhost
  eureka: localhost
  auth: localhost

server:
  port: 8054

eureka:
  client:
    serviceUrl:
      defaultZone: http://${host.eureka}:8051/eureka/

spring:
  zipkin:
    baseUrl: http://${host.zipkin}:9411/
  sleuth:
    sampler:
      probability: 1.0

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

---
spring:
  profiles: deployment

host:
  zipkin: zipkin
  eureka: discovery-service
  auth: localhost