version: '3'

services:
  config-service:
    container_name: config-service
    restart: always
    image: config-service:latest
    build:
      context: ./config-service
    environment:
    - SPRING_PROFILES_ACTIVE=native

  discovery-service:
    container_name: discovery-service
    restart: always
    image: discovery-service:latest
    build:
      context: ./discovery-service
    ports:
    - 8051:8051
    depends_on:
    - config-service
    environment:
    - SPRING_PROFILES_ACTIVE=deployment