version: '3'

services:
  config-service:
    container_name: config-service
    restart: always
    image: config-service:latest
    build:
      context: ./config-service
    ports:
      - 8050:8050
    environment:
    - SPRING_PROFILES_ACTIVE=native

  discovery-service:
    container_name: discovery-service
    restart: always
    image: discovery-service:latest
    build:
      context: ./discovery-service
    ports:
    - 8051:8051
    depends_on:
    - config-service
    environment:
    - SPRING_PROFILES_ACTIVE=deployment

  auth-service:
    container_name: auth-service
    restart: always
    image: auth-service:latest
    build:
      context: ./auth-service
    ports:
    - 8052:8052
    depends_on:
    - discovery-service
    environment:
    - SPRING_PROFILES_ACTIVE=deployment

  proxy-service:
    container_name: proxy-service
    restart: always
    image: proxy-service:latest
    build:
      context: ./proxy-service
    ports:
    - 8053:8053
    depends_on:
    - discovery-service
    environment:
    - SPRING_PROFILES_ACTIVE=deployment

#  organization-service:
#    container_name: organization-service
#    restart: always
#    image: organization-service:latest
#    build:
#      context: ./organization-service
#    ports:
#    - 8054:8054
#    depends_on:
#    - discovery-service
#    environment:
#    - SPRING_PROFILES_ACTIVE=deployment

#  department-service:
#    container_name: department-service
#    restart: always
#    image: department-service:latest
#    build:
#      context: ./department-service
#    ports:
#    - 8055:8055
#    depends_on:
#    - discovery-service
#    environment:
#    - SPRING_PROFILES_ACTIVE=deployment

#  employee-service:
#    container_name: employee-service
#    restart: always
#    image: employee-service:latest
#    build:
#      context: ./employee-service
#    ports:
#    - 8056:8056
#    depends_on:
#    - discovery-service
#    environment:
#    - SPRING_PROFILES_ACTIVE=deployment

  ui-service:
    container_name: ui-service
    restart: always
    image: ui-service:latest
    build:
      context: ./ui-service
    ports:
    - 8057:8057
    depends_on:
    - discovery-service
    environment:
    - SPRING_PROFILES_ACTIVE=deployment